parserOptions:
  ecmaVersion: 2017
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true
  mocha: true

extends: 'htmlacademy/es6'

# Nice way to get rid of no-unused-expressions linter error with chai
#overrides: [
#    {
#        files: '*.test.js',
#        rules: {
#            "no-unused-expressions": 'off'
#        }
#    }
#]
